//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ciudad()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
        }
    
        public string CODCIUDAD { get; set; }
        public string DESCIUDAD { get; set; }
        public string CODPAIS { get; set; }
        public string iddepa { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<System.DateTime> datetrans { get; set; }
        public Nullable<bool> trans { get; set; }
        public string CODEMPRESA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
    }
}
